# -*- coding: utf-8 -*-
"""Trabalho_final_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14JD2HuHA2Gzu1-GcHOTDTJSIbijt2NzQ
"""

import streamlit as st
import pandas as pd
import requests
import time
from urllib.parse import quote_plus
# ----------------------------------------------------
# Configuração da página
# ----------------------------------------------------

st.set_page_config(
    page_title="Violência contra a Mulher no Brasil",
    page_icon="📰",
    layout="wide"
)

st.title("📰 Agente IA - Violência contra a Mulher no Brasil")
st.warning("""
⚠️ **Aviso**

Este aplicativo utiliza a **GDELT 2.1 Document API**.

• Não requer chave de API.

• A cobertura histórica é muito melhor a partir de 2015.

• Consultas para períodos anteriores podem retornar poucos ou nenhum resultado.

• A API possui limite de resultados por consulta.
""")

st.markdown("""
Este agente utiliza **Processamento de Linguagem Natural (PLN)** para identificar,
a partir de notícias publicadas em portais online, ocorrências de violência contra a mulher
no Brasil para um ano específico.

**Fluxo do projeto**

1. Pesquisar notícias;
2. Aplicar PLN;
3. Identificar o estado citado;
4. Gerar tabelas;
5. Gerar gráficos;
6. Produzir mapa temático.
""")

# ----------------------------------------------------
# Barra lateral
# ----------------------------------------------------

st.sidebar.title("Configuração")
st.sidebar.success("Fonte de dados: GDELT 2.1 Document API")
from datetime import date

# ----------------------------------------------------
# Período da pesquisa
# ----------------------------------------------------

st.sidebar.subheader("Período da pesquisa")

data_inicial = st.sidebar.date_input(
    "Data inicial",
    value=date(2024, 1, 1),
    min_value=date(2015, 1, 1),
    max_value=date.today(),
    format="DD/MM/YYYY"
)

data_final = st.sidebar.date_input(
    "Data final",
    value=date(2024, 12, 31),
    min_value=date(2015, 1, 1),
    max_value=date.today(),
    format="DD/MM/YYYY"
)

if data_final < data_inicial:
    st.sidebar.error("A data final deve ser maior ou igual à data inicial.")
    st.stop()
# ----------------------------------------------------
# Consulta
# ----------------------------------------------------

PALAVRAS = [
    '"violência contra mulher"',
    '"violência doméstica"',
    'feminicídio'
]
quantidade = st.sidebar.selectbox(
    "Máximo de notícias por palavra-chave",
    [10, 20, 50, 100],
    index=0
)
buscar = st.sidebar.button(
    "🔎 Buscar Notícias",
    use_container_width=True
)

# ----------------------------------------------------
# Inicialização
# ----------------------------------------------------
inicio = data_inicial.strftime("%Y%m%d000000")
fim = data_final.strftime("%Y%m%d235959")
# ----------------------------------------------------
# Área principal
# ----------------------------------------------------

c1,c2,c3 = st.columns(3)

c1.metric(
    "Período",
    f"{data_inicial.strftime('%d/%m/%Y')} até {data_final.strftime('%d/%m/%Y')}"
)

c2.metric(
    "Fonte",
    "GDELT 2.1"
)

c3.metric(
    "Máximo de notícias",
    quantidade
)

st.divider()

# ----------------------------------------------------
# Busca
# ----------------------------------------------------
if buscar:

    with st.spinner("Consultando a GDELT..."):

        try:

            inicio = data_inicial.strftime("%Y%m%d000000")
            fim = data_final.strftime("%Y%m%d235959")

            headers = {
    "User-Agent":
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
}

            todos = []

    for palavra in PALAVRAS:
            consulta = quote_plus(palavra)

            url = (
    "https://api.gdeltproject.org/api/v2/doc/doc"
    f"?query={consulta}"
    "&mode=ArtList"
    "&format=json"
    "&sort=DateDesc"
    "&language=Portuguese"
    f"&maxrecords={quantidade}"
    f"&startdatetime={inicio}"
    f"&enddatetime={fim}"
)
                resposta = requests.get(
                    url,
                    headers=headers,
                    timeout=60
                )

                if resposta.status_code != 200:
                    st.warning(
                        f"Consulta '{palavra}' retornou código {resposta.status_code}."
                    )
                    continue

    try:
        resultado = resposta.json()
    except ValueError:
        st.error("A GDELT retornou uma resposta inválida.")
        st.code(resposta.text[:1000])
        st.stop()

                artigos = resultado.get("articles", [])

                for artigo in artigos:

                    todos.append({

                        "Palavra-chave": palavra,

                        "Data": artigo.get("seendate"),

                        "Título": artigo.get("title"),

                        "Fonte": artigo.get("domain"),

                        "Idioma": artigo.get("language"),

                        "URL": artigo.get("url")

                    })

                time.sleep(2)

            if len(todos) == 0:

                st.warning("Nenhuma notícia encontrada.")

            else:

                df = pd.DataFrame(todos)

                df.drop_duplicates(
                    subset=["URL"],
                    inplace=True
                )

                st.success(
                    f"{len(df)} notícias encontradas."
                )

                st.dataframe(
                    df.head(20),
                    use_container_width=True,
                    hide_index=True
                )

                st.download_button(
                    "📥 Baixar CSV",
                    df.to_csv(index=False).encode("utf-8"),
                    "noticias.csv",
                    "text/csv"
                )

        except Exception as erro:

            st.error(f"Erro: {erro}")
