# -*- coding: utf-8 -*-
"""Trabalho_final_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14JD2HuHA2Gzu1-GcHOTDTJSIbijt2NzQ
"""

import streamlit as st
import pandas as pd
from newsapi import NewsApiClient

# ----------------------------------------------------
# Configuração da página
# ----------------------------------------------------

st.set_page_config(
    page_title="Violência contra a Mulher no Brasil",
    page_icon="📰",
    layout="wide"
)

st.title("📰 Agente IA - Violência contra a Mulher no Brasil")

st.markdown("""
Este agente utiliza **Processamento de Linguagem Natural (PLN)** para identificar,
a partir de notícias publicadas em portais online, ocorrências de violência contra a mulher
no Brasil para um ano específico.

**Fluxo do projeto**

1. Pesquisar notícias;
2. Aplicar PLN;
3. Identificar o estado citado;
4. Gerar tabelas;
5. Gerar gráficos;
6. Produzir mapa temático.
""")

# ----------------------------------------------------
# Barra lateral
# ----------------------------------------------------

st.sidebar.title("Configuração")

st.sidebar.subheader("NewsAPI")

col1, col2 = st.sidebar.columns([5,1])

with col1:

    api_key = st.text_input(
        "Chave da NewsAPI",
        type="password",
        placeholder="Cole sua chave aqui..."
    )

with col2:

    st.link_button(
        "ℹ️",
        "https://newsapi.org/register",
        help="""
Crie gratuitamente sua chave na NewsAPI.

Clique para acessar o site oficial.
"""
    )

if not api_key:

    st.sidebar.info(
        """
Para utilizar o sistema é necessário possuir uma chave da NewsAPI.

Clique no botão ℹ️ para criar gratuitamente sua chave.
"""
    )

from datetime import date

# ----------------------------------------------------
# Período da pesquisa
# ----------------------------------------------------

st.sidebar.subheader("Período da pesquisa")

data_inicial = st.sidebar.date_input(
    "Data inicial",
    value=date(2024, 1, 1),
    min_value=date(2010, 1, 1),
    max_value=date.today(),
    format="DD/MM/YYYY"
)

data_final = st.sidebar.date_input(
    "Data final",
    value=date(2024, 12, 31),
    min_value=date(2010, 1, 1),
    max_value=date.today(),
    format="DD/MM/YYYY"
)

if data_final < data_inicial:
    st.sidebar.error("A data final deve ser maior ou igual à data inicial.")
    st.stop()
# ----------------------------------------------------
# Consulta
# ----------------------------------------------------

PALAVRAS_CHAVE = (
    '"violência contra mulher" OR '
    'feminicídio OR '
    '"violência doméstica"'
)

st.sidebar.markdown("### Palavras-chave utilizadas")
st.sidebar.info(PALAVRAS_CHAVE)

consulta = PALAVRAS_CHAVE

quantidade = st.sidebar.selectbox(
    "Quantidade máxima",
    [20,50,100,200],
    index=1
)

buscar = st.sidebar.button(
    "🔎 Buscar Notícias",
    use_container_width=True
)

# ----------------------------------------------------
# Inicialização
# ----------------------------------------------------

newsapi = None

if api_key:

    try:

        newsapi = NewsApiClient(api_key=api_key)

        st.sidebar.success("NewsAPI conectada.")

    except Exception as erro:

        st.sidebar.error(str(erro))

# ----------------------------------------------------
# Área principal
# ----------------------------------------------------

c1,c2,c3 = st.columns(3)

c1.metric(
    "Período",
    f"{data_inicial.strftime('%d/%m/%Y')} até {data_final.strftime('%d/%m/%Y')}"
)

c2.metric(
    "API",
    "Conectada" if newsapi else "Não conectada"
)

c3.metric(
    "Máximo de notícias",
    quantidade
)

st.divider()

# ----------------------------------------------------
# Busca
# ----------------------------------------------------
if buscar:

    if not newsapi:

        st.error("Informe uma chave válida da NewsAPI.")

    else:

        with st.spinner("Pesquisando notícias..."):

            try:

                resultado = newsapi.get_everything(
                    q=consulta,
                    from_param=data_inicial.strftime("%Y-%m-%d"),
                    to=data_final.strftime("%Y-%m-%d"),
                    language="pt",
                    sort_by="publishedAt",
                    page_size=quantidade
                )

                artigos = resultado["articles"]

                dados = []

                for artigo in artigos:

                    dados.append({
                        "Data": artigo["publishedAt"][:10],
                        "Fonte": artigo["source"]["name"],
                        "Título": artigo["title"],
                        "Descrição": artigo["description"],
                        "URL": artigo["url"]
                    })

                df = pd.DataFrame(dados)

                st.success(f"{len(df)} notícias encontradas.")

                st.dataframe(
                    df,
                    use_container_width=True,
                    hide_index=True
                )

                csv = df.to_csv(index=False).encode("utf-8")

                st.download_button(
                    "📥 Baixar CSV",
                    csv,
                    "noticias.csv",
                    "text/csv"
                )

            except Exception as erro:

                st.error(f"Erro: {erro}")
